image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build

build:armhf:
  stage: build
  before_script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - mkdir images
  script:
    - docker build --pull --build-arg ARCH=armhf --build-arg GOARCH=arm --build-arg GOARM=6 -t $CI_REGISTRY_IMAGE:armhf .
    - docker save -o images/cloudflared-armhf.tar $CI_REGISTRY_IMAGE:armhf
  artifacts:
    paths:
      - images

build:arm64:
  stage: build
  before_script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - mkdir images
  script:
    - docker build --pull --build-arg ARCH=arm64 --build-arg GOARCH=arm64 -t $CI_REGISTRY_IMAGE:arm64 .
    - docker save -o images/cloudflared-arm64.tar $CI_REGISTRY_IMAGE:arm64
  artifacts:
    paths:
      - images

build:amd64:
  stage: build
  before_script:
    - mkdir images
  script:
    - docker build --pull --build-arg ARCH=amd64 --build-arg GOARCH=amd64 -t $CI_REGISTRY_IMAGE:amd64 .
    - docker save -o images/cloudflared-amd64.tar $CI_REGISTRY_IMAGE:amd64
  artifacts:
    paths:
      - images
